/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGradeRouteImport } from './routes/_authenticated/grade'
import { Route as AuthenticatedMeetRouteImport } from './routes/_authenticated/meet'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedTeachRouteImport } from './routes/_authenticated/teach'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalProgramRouteImport } from './routes/_authenticated/portal/program'
import { Route as AuthenticatedPortalRegisterRouteImport } from './routes/_authenticated/portal/register'
import { Route as AuthenticatedPortalResultsRouteImport } from './routes/_authenticated/portal/results'
import { Route as AuthenticatedPortalExamExamIdRouteImport } from './routes/_authenticated/portal/exam.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradeRoute = AuthenticatedGradeRouteImport.update({
  id: '/grade',
  path: '/grade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetRoute = AuthenticatedMeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeachRoute = AuthenticatedTeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalProgramRoute =
  AuthenticatedPortalProgramRouteImport.update({
    id: '/portal/program',
    path: '/portal/program',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalRegisterRoute =
  AuthenticatedPortalRegisterRouteImport.update({
    id: '/portal/register',
    path: '/portal/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalResultsRoute =
  AuthenticatedPortalResultsRouteImport.update({
    id: '/portal/results',
    path: '/portal/results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalExamExamIdRoute =
  AuthenticatedPortalExamExamIdRouteImport.update({
    id: '/portal/exam/$examId',
    path: '/portal/exam/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grade': typeof AuthenticatedGradeRoute
  '/meet': typeof AuthenticatedMeetRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/teach': typeof AuthenticatedTeachRoute
  '/test': typeof AuthenticatedTestRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/program': typeof AuthenticatedPortalProgramRoute
  '/portal/register': typeof AuthenticatedPortalRegisterRoute
  '/portal/results': typeof AuthenticatedPortalResultsRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/exam/$examId': typeof AuthenticatedPortalExamExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grade': typeof AuthenticatedGradeRoute
  '/meet': typeof AuthenticatedMeetRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/teach': typeof AuthenticatedTeachRoute
  '/test': typeof AuthenticatedTestRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/program': typeof AuthenticatedPortalProgramRoute
  '/portal/register': typeof AuthenticatedPortalRegisterRoute
  '/portal/results': typeof AuthenticatedPortalResultsRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/exam/$examId': typeof AuthenticatedPortalExamExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grade': typeof AuthenticatedGradeRoute
  '/_authenticated/meet': typeof AuthenticatedMeetRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/teach': typeof AuthenticatedTeachRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/portal/program': typeof AuthenticatedPortalProgramRoute
  '/_authenticated/portal/register': typeof AuthenticatedPortalRegisterRoute
  '/_authenticated/portal/results': typeof AuthenticatedPortalResultsRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/exam/$examId': typeof AuthenticatedPortalExamExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/grade'
    | '/meet'
    | '/notifications'
    | '/teach'
    | '/test'
    | '/api/chat'
    | '/portal/program'
    | '/portal/register'
    | '/portal/results'
    | '/portal/'
    | '/portal/exam/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/grade'
    | '/meet'
    | '/notifications'
    | '/teach'
    | '/test'
    | '/api/chat'
    | '/portal/program'
    | '/portal/register'
    | '/portal/results'
    | '/portal'
    | '/portal/exam/$examId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/grade'
    | '/_authenticated/meet'
    | '/_authenticated/notifications'
    | '/_authenticated/teach'
    | '/_authenticated/test'
    | '/api/chat'
    | '/_authenticated/portal/program'
    | '/_authenticated/portal/register'
    | '/_authenticated/portal/results'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/exam/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grade': {
      id: '/_authenticated/grade'
      path: '/grade'
      fullPath: '/grade'
      preLoaderRoute: typeof AuthenticatedGradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meet': {
      id: '/_authenticated/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof AuthenticatedMeetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teach': {
      id: '/_authenticated/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof AuthenticatedTeachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/program': {
      id: '/_authenticated/portal/program'
      path: '/portal/program'
      fullPath: '/portal/program'
      preLoaderRoute: typeof AuthenticatedPortalProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/register': {
      id: '/_authenticated/portal/register'
      path: '/portal/register'
      fullPath: '/portal/register'
      preLoaderRoute: typeof AuthenticatedPortalRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/results': {
      id: '/_authenticated/portal/results'
      path: '/portal/results'
      fullPath: '/portal/results'
      preLoaderRoute: typeof AuthenticatedPortalResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/exam/$examId': {
      id: '/_authenticated/portal/exam/$examId'
      path: '/portal/exam/$examId'
      fullPath: '/portal/exam/$examId'
      preLoaderRoute: typeof AuthenticatedPortalExamExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGradeRoute: typeof AuthenticatedGradeRoute
  AuthenticatedMeetRoute: typeof AuthenticatedMeetRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedTeachRoute: typeof AuthenticatedTeachRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedPortalProgramRoute: typeof AuthenticatedPortalProgramRoute
  AuthenticatedPortalRegisterRoute: typeof AuthenticatedPortalRegisterRoute
  AuthenticatedPortalResultsRoute: typeof AuthenticatedPortalResultsRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalExamExamIdRoute: typeof AuthenticatedPortalExamExamIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGradeRoute: AuthenticatedGradeRoute,
  AuthenticatedMeetRoute: AuthenticatedMeetRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedTeachRoute: AuthenticatedTeachRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedPortalProgramRoute: AuthenticatedPortalProgramRoute,
  AuthenticatedPortalRegisterRoute: AuthenticatedPortalRegisterRoute,
  AuthenticatedPortalResultsRoute: AuthenticatedPortalResultsRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalExamExamIdRoute: AuthenticatedPortalExamExamIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
